### ISSUE TITLE
Switch from Room.databaseBuilder(Application, ...) to Room.databaseBuilder(Context, ...)

### ISSUE THREAD

**Issue by cheskos** [androidx-releases/Room#4]
Hi. 

More than an actual issue this is a question. I accidentally passed the `application` instance to my database builder and that code is now in Production. After realizing the mistake and changing it, upon first launch upgrading from a previous build that used the "bad" argument, I now see this is logcat:

```
2022-10-19 18:13:19.197 1802-2177/com.android.phone E/SQLiteLog: (3850) statement aborts at 70: [UPDATE sms SET type=? WHERE type = 4] disk I/O error
2022-10-19 18:13:19.198 1802-2177/com.android.phone E/DatabaseUtils: Writing exception to parcel
    android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 3850)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
        at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1576)
        at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1522)
        at com.android.providers.telephony.SmsProvider.update(SmsProvider.java:699)
        at android.content.ContentProvider$Transport.update(ContentProvider.java:325)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:222)
        at android.os.Binder.execTransact(Binder.java:446)
2022-10-19 18:13:19.198 19435-19468/com.android.mms E/SqliteWrapper: Catch a SQLiteException when update: 
    android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 3850)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
        at android.content.ContentProviderProxy.update(ContentProviderNative.java:567)
        at android.content.ContentResolver.update(ContentResolver.java:1333)
        at android.database.sqlite.SqliteWrapper.update(SqliteWrapper.java:79)
        at com.android.mms.transaction.SmsReceiverService.moveOutboxMessagesToQueuedBox(SmsReceiverService.java:417)
        at com.android.mms.transaction.SmsReceiverService.handleSendInactiveMessage(SmsReceiverService.java:241)
        at com.android.mms.transaction.SmsReceiverService.access$500(SmsReceiverService.java:71)
        at com.android.mms.transaction.SmsReceiverService$ServiceHandler.handleMessage(SmsReceiverService.java:216)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2022-10-19 18:13:19.198 19435-19468/com.android.mms E/AndroidRuntime: FATAL EXCEPTION: Mms
    Process: com.android.mms, PID: 19435
    android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 3850)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
        at android.content.ContentProviderProxy.update(ContentProviderNative.java:567)
        at android.content.ContentResolver.update(ContentResolver.java:1333)
        at android.database.sqlite.SqliteWrapper.update(SqliteWrapper.java:79)
        at com.android.mms.transaction.SmsReceiverService.moveOutboxMessagesToQueuedBox(SmsReceiverService.java:417)
        at com.android.mms.transaction.SmsReceiverService.handleSendInactiveMessage(SmsReceiverService.java:241)
        at com.android.mms.transaction.SmsReceiverService.access$500(SmsReceiverService.java:71)
        at com.android.mms.transaction.SmsReceiverService$ServiceHandler.handleMessage(SmsReceiverService.java:216)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2022-10-19 18:13:19.201 19435-19468/com.android.mms I/Process: Sending signal. PID: 19435 SIG: 9
2022-10-19 18:13:19.202 1528-19469/system_process E/DropBoxManagerService: Can't write: system_app_crash
    java.io.FileNotFoundException: /data/system/dropbox/drop184.tmp: open failed: EROFS (Read-only file system)
        at libcore.io.IoBridge.open(IoBridge.java:456)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
        at com.android.server.DropBoxManagerService.add(DropBoxManagerService.java:211)
        at android.os.DropBoxManager.addText(DropBoxManager.java:269)
        at com.android.server.am.ActivityManagerService$20.run(ActivityManagerService.java:12006)
     Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
```

Is there anything I should worry about? If so, is there a way to fix it? 

For clarity, I was doing:
`val builder = Room.databaseBuilder(app.applicationContext, MyDB::class.java, "myDB.db")`

Much appreciated.

**Comment by cheskos** [comment]
Not able to repro, must've been something else.
